#   Übersetzt von Grabenkind
#   Bei Rechtschreibfehlern bitte kontaktieren
#   Kontakt: grabenkind@gmail.com
#   
#   Dieses Plugin wird von hackerG7 entwickelt!
#   Alle Fehler die keine Rechtschreibfehler sind,
#   müssen dem Entwickler selbst berichtet werden.

systemName: '&8【&aGKAntiCheat&8】'
successString: '&aGK-Anti-Cheat Test erfolgreich bestanden'
failString: '&cDu hast den GK-Anti-Cheat Test nicht bestanden.'
kickString: '&cDu wurdest %amount% mal mit einem gehackten Client identifiziert. Bitte wechsel zu einer legalen Version, anderseits droht dir ein Ban!'
kickSeconds: 20
whiteString: '&eWhitelist'
failsString: '&cFails'
hacksString: '&4Hacks'
addWhiteString: '&aSpieler erfolgreich in die Whitelist aufgenommen: '
removeWhiteString: '&aSpieler erfolgreich von der Whitelist entfernt: ' 
cannotFindPlayerString: '&cSpieler kann nicht gefunden werden: ' 
remainingTimeString: 'Verbleibend' 
secondString: 'Sek.'
reloadString: '&a&aReload abgeschlossen'
topString: '&e------&aBitte klicke auf die Schaltfläche&e------'
bottomString: '&e------&aBitte klicke auf die Schaltfläche&e------'
helpList:
- ---------------------------------------------------
- /gkac help                        list GKAntiCheat commands help
- /gkac reload                     reload the config
- /gkac add <player>             add player into white list
- /gkac remove <player>        remove player from white list
- /gkac check <player>          check player's record
- ---------------------------------------------------
